import * as THREE from 'three';
import { Rig, PoseBuffer, eulerDeg } from './Rig.js';
import { CLIPS, CLIP_NAMES, MISSING, compile, sampleInto, sampleCane } from './Clips.js';
import { MIXAMO_CLIPS } from './MixamoClips.js';
import { GODOT_CLIPS } from './GodotClips.js';

/**
 * Animation.js — the ANIMATION module (AGENTS.md §4.7).
 *
 * MOVEMENT says *what Sly is doing*; this decides *what that looks like*. Nothing outside
 * this file ever touches a bone.
 *
 * The frame, in order:
 *
 *   1. **Blend tree** — an 8-way locomotion blend (idle/walk/run/run_fast × stand/sneak/crouch)
 *      plus turn-in-place, all sharing one stride phase so a walk can cross-fade into a run
 *      mid-step without the feet swapping or skating.
 *   2. **Tracks** — explicit clips MOVEMENT asked for, layered over the tree and cross-fading
 *      against it. One-shots sit on top and hand the body back when they end.
 *   3. **Additive** — breathing, lean into turns and acceleration, landing squash. These ride
 *      on top of the keyframes so they never fight the authored pose.
 *   4. **Procedural** (Rig.js) — look-at, tail spring chain, cap/ear overshoot, hit impulses,
 *      and two-bone foot IK planted on the real ground normal.
 *
 * Everything degrades: no CHARACTER, no COLLISION, no MOVEMENT — it still renders a pose.
 */

/* ========================================================================== */

export const ANIM_TUNE = {
  /* --- blending --- */
  fade: 0.12,               // default cross-fade (§4.7 default)
  treeFade: 0.18,           // how fast the locomotion tree takes the body back
  stanceRate: 7.0,          // sneak/crouch stance cross-fade rate
  speedSmooth: 9.0,         // low-pass on locomotion speed; raw speed makes the tree buzz

  /* --- stride phase --- */
  strideMin: 0.35,          // cycles/s floor so a crawl at 0.2 m/s still animates
  strideMax: 3.4,           // cycles/s ceiling — a physics spike must not flicker the legs
  turnCycle: 1.7,           // rad of yaw per turn-in-place cycle

  /* --- speed axis breakpoints (m/s) --- */
  standAxis: [0.0, 2.6, 5.4, 7.6],
  sneakAxis: [0.0, 1.5],
  crouchAxis: [0.0, 1.7],
  moveFloor: 0.22,          // below this he is standing still, whatever the physics says

  /* --- lean --- */
  leanTurn: 4.6,            // degrees of bank per rad/s of turn
  leanTurnMax: 15,
  leanAccel: 0.55,          // degrees of pitch per m/s² of acceleration
  leanAccelMax: 11,
  leanRate: 6.5,

  /* --- breathing (idles only) --- */
  breathRate: 0.44,         // Hz
  breathAmp: 2.1,           // degrees at the chest
  breathScale: 0.022,

  /* --- landing squash, §6: 0.82 scale-y over 90 ms, ease-out back --- */
  squashIn: 0.09,
  squashOut: 0.26,
  squashScale: 0.18,        // 1 - 0.82
  squashKnee: 26,           // degrees of extra knee fold at full squash

  /* --- procedural layer weights --- */
  lookWeight: 1.0,
  ikGround: 1.0,
  ikAirRate: 5.0,
};

/* ========================================================================== */
/*  clip-set registration — which data drives the rig                         */
/* ========================================================================== */

/**
 * `MIXAMO_CLIPS` (generated by `tools/mixamo2clips.mjs`) is 16 clips retargeted onto RIG3 from a
 * fan project's authored animation. It is emitted in `Clips.js`'s **authoring** format on purpose,
 * so it comes through `Clips.js`'s own `compile()` — same eases, same `eulerDeg`, same sparse-key
 * rule, sampled by the same `slerp`. `compile()` is exported for exactly this; the alternative was
 * a second compiler here, and §212's cost was a second, subtly different account of the
 * authoring→runtime interchange being reasoned about as if it were the real one. One copy.
 *
 * ── The map is 16 → 14, and it is not a 1:1 substitution ────────────────────────────────
 * §4.7 requires 52 clip names. Mixamo supplies 13 usable sources covering 14 of them, so **38 of
 * 52 have no counterpart and stay procedural whatever the token says**. `walk_side_left/right`
 * have no game slot at all (nothing in the 52 strafes) and `fall_pose_02` is a 0.067 s static pose
 * with nowhere sensible to go; all three are deliberately unused rather than given an invented job.
 *
 * ── What Mixamo cannot supply, and how the mixed regime fills it ────────────────────────
 * Mixamo has no tail, no cane, no ears, no brow, no jaw, no cap. That is 10 of RIG3's 31 bones,
 * and four of them are the tail — "half his silhouette" by `Rig.js`'s own account. So the mixed
 * regime is stated as ONE rule rather than a list of exceptions:
 *
 *     a mixed clip takes Mixamo's track for every bone Mixamo has, and the procedural
 *     counterpart's track — time-scaled onto the new duration — for every bone it does not,
 *     plus that counterpart's cane track.
 *
 * Time-scaling is what makes it a splice rather than a collision: `walk` is 1.0 s and
 * `walk_forward` is 1.7 s, and an unscaled donor track would run out at 1.0 s and freeze the tail
 * for the remaining 0.7 s of every cycle. Both are cycles, so scaling the donor's key times by
 * `durNew/durOld` phase-matches them.
 *
 * `mixamo-pure` exists to isolate that fill: same 14 clips with NO donor tracks, so the tail, cane
 * and face sit at bind and only the spring layers move them. It is the arm that says how much of
 * the mixed regime's look is Mixamo and how much is the procedural set still doing the work.
 */
/**
 * `GODOT_CLIPS` (generated by `tools/godot2clips.mjs`) is the fan project's own authored
 * movement set — the same repository, same rig family and same licence status as the mesh —
 * retargeted onto RIG3 in the authoring format, through the same `compile()` and the same donor
 * fill as the Mixamo set. **This is the DEFAULT regime**, by the user's explicit instruction
 * ("use the repo's animations for movement"): a verb is swapped to the repo's clip when the
 * audit says the swap survives on camera, and the alias below IS the audited set — everything
 * not listed stays procedural through the fill rule, so the swap surface is exactly this table.
 *
 * ── The alias entries carry DELIVERED timing, not authored timing ───────────────────────────
 * `dur` rescales the source clip onto the window OUR moveset actually shows — §474.3's own
 * rule, and the §474 twirl already paid for ignoring it once. The window is physics, not
 * taste: `doubleJumpV0` 9.90 / g 24 puts apex at 0.4125 s, so a HELD flip at `dur` 0.41 ends
 * exactly as `fall` re-bases; a TAPPED one cuts the state at ~0.167 s and demotes over a
 * 0.12 s fade (§474.3, measured), and the source front-loads its rotation (complete by 0.60 of
 * the clip), so at 0.41 the 360° closes ≈ 0.25 s — inside the tapped window, and past 180° by
 * the cut so even the demote blend resolves FORWARD. Their own delivered number does not
 * transfer and is not used: the tree plays FrontFlip through `TimeScale 2/scale = 0.85`
 * (`sly_cooper_anims_4.tscn`, never rewritten at runtime — checked, and an earlier draft of
 * this comment claimed 2× here, read out of a model rather than the file), i.e. ≈ 0.88 s
 * delivered in THEIR jump arc, which no 0.41 s rise of ours can carry.
 *
 * ── Why the flip arrives at all (the §474.1 class, dodged twice) ────────────────────────────
 * The source authors the 360° on control bones ABOVE the pelvis (`RotateCTL`); a local-track
 * copy would have delivered a flip with no rotation in it — the identity authored into a
 * channel the copy discards, §474.1's failure exactly. godot2clips retargets WORLD deltas, so
 * ancestor motion lands in the pelvis by construction. And the export's own final quarter-turn
 * is broken (the baked curve runs +282° then snaps backward to identity in 0.05 s — at their
 * 0.85× the snap spans ~3.5 rendered frames and their game simply shows it, a fast blur-frame
 * unwind); sampled at 20 Hz and played through Clips.js' per-segment slerp, at most one
 * emitted key lands inside the snap and the short arc runs the flip FORWARD through +360 with
 * an 18° overshoot-and-settle. Both are measured in godot2clips' report (src→emit sweep
 * 0°→−360°), not assumed here.
 */
/**
 * §479.7 — the launch's delivered pace, and why it is THEIR number this time. The user: "Slow
 * down the jump animation." The §478 accounting rerun for the jump family, all read from the
 * checkout, none assumed: their tree plays the ground jump through
 * `parameters/TimeScale/scale = 0.75` (`sly_cooper_anims_4.tscn:48498`; the path is
 * jump_state/jump_floor → TimeScale → jump → `Library_Sly_19/Jump`), so their 0.5 s bake READS
 * at 0.667 s — and at 1.0× we were delivering the same launch 1.33× faster than their own game
 * ever showed it. Unlike the flip (§478.3), the launch has NO closure constraint — a somersault
 * must complete its 360° inside the airtime, a launch pose just launches and hands off to
 * apex/fall — so the right timescale is their delivered rate verbatim, not a compression into
 * our window: at 0.75× our held rise (jumpV0 11 / g 24 = 0.458 s) shows 69% of the clip by
 * apex; their own arc (8.06 / 16.25 = 0.496 s rise, their script's own derivation at
 * `player__sly.gd:129`) shows 74%. Same read, same fraction, no cut. `Falling` was checked the
 * same way and is NOT retimed: both its tree bindings (`Hat Fall Sub`→`Library_Sly_14/Falling`,
 * `nodes/fall`→`Library_Sly_19/Falling`) are bare AnimationNodeAnimation nodes — no TimeScale
 * in the path — so 1.0× IS its natural delivered rate, and the clip is a near-static held pose
 * besides (max 60 Hz world step 1°, godot2clips' report).
 */
const JUMP_NATURAL_RATE = 0.75;   // their TimeScale/scale for jump_floor, verbatim

const GODOT_ALIAS = {
  /* game name       source + delivered timing (see the window derivation above).
     THE AUDITED SET (§479): each row is a verb where the repo authored a clip for the same
     beat; each survives only with frames in shots/ (moves1 pairs) behind it. Rows the audit
     REFUSED are recorded in §479, not deleted silently. Sources play at authored duration
     unless a `dur` says otherwise; walk/run/rail carry strides DERIVED from their own foot
     geometry (godot2clips' report), so the tree rate-matches them exactly as the hand set. */
  double_jump:   { src: 'FrontFlip', dur: 0.41 },
  walk:          'Walk',
  run:           'Run',
  run_fast:      'Run',            // no second run in the source; the tree needs the node filled
  jump_rise:     { src: 'Jump', rate: JUMP_NATURAL_RATE },
  jump_fall:     'Falling',
  land_soft:     'Landing',
  ledge_hang:    'LedgeGrab Idle',
  pole_climb:    'PoleClimbing',
  rail_walk:     'railrun',
  spire_balance: 'SpireJumpIdle',
  spire_land:    'SpireJumplanding',

  /* §479.8 — the combat + pickpocket port ("check to see if the attack and pickpocket
     animations were properly ported"). Their ground attack is ONE clip — `Canehit`, fired on
     every square press (`Hit Transition/hit_floor`, player__sly.gd:640, no TimeScale) — so all
     three combo slots play it, whole and at natural rate, exactly as their tree fires it.

     WHERE THE CONTACT IS, measured, not derived (§442.3). An earlier pass of this same port
     read `Canehit`'s peak hand SPEED (14.8 m/s, authored t 0.42) as the strike and trimmed
     0.25–0.30 s off the head to bring it forward. That was backwards, and the reach curve says
     so: handR travels from 0.09 m BEHIND the hips at t 0 to 0.92 m in FRONT of them by t 0.10
     — that whip is the strike — then hovers 0.69–0.88 through the follow-through and snaps back
     to guard between t 0.40 and 0.45. The 14.8 m/s peak is the RECOVERY, the hand leaving the
     target. Trimming to 0.25 deleted the entire attack and shipped only the yank back.
     Contact is at **t 0.10 of the clip's own timeline**, so the clip is played from its own
     frame 0 and no trim exists any more.

     The measure is max forward reach of the swinging hand relative to the hips, and it is
     calibrated on our own procedural set in the same pass: proc `cane_combo_1` peaks at
     t 0.150 and the house declares its `cane_hit` at exactly 0.150 (combos 2 and 3 within
     35–70 ms). A measure that reproduces the house's own authored contact is measuring contact.

     0.10 s after the press is inside the window our own combos already use (0.13–0.21 s) and
     slightly snappier; nothing gates on it, because damage resolves ON the press
     (Guard.js:1770) — `cane_hit` is the visual/audio contact marker, so it belongs on the
     visual contact. Hand-carried rather than inherited: the splice's donor rule time-SCALES
     proc's events by dur ratio (0.15 → 0.163 here), which would sit 63 ms past the real
     contact. combo_3 keeps its paired `land` stomp on the same beat. Lunge, damage and shake
     stay the moveset's. LIMIT, stated not hidden: their tree has one ground attack, so our
     three chain slots are the same swing three times — faithful to the reference, and less
     varied than the proc set it replaces.

     `PickPocket` keeps its natural reach (max extension at t 0.25, settled by ~0.6) and cuts
     the export's 4 s idle-bake tail at 1.1 s — the proc clip's own window (pickTime 0.55 exits
     the state; the one-shot's remainder holds the reach over the fade). */
  cane_combo_1:  { src: 'Canehit', events: [{ t: 0.10, n: 'cane_hit', d: { index: 1 } }] },
  cane_combo_2:  { src: 'Canehit', events: [{ t: 0.10, n: 'cane_hit', d: { index: 2 } }] },
  cane_combo_3:  { src: 'Canehit', events: [{ t: 0.10, n: 'cane_hit', d: { index: 3 } },
                                            { t: 0.10, n: 'land', d: { force: 0.5 } }] },
  pickpocket:    { src: 'PickPocket', until: 1.1 },

  /* The `CaneSwing` family turned out NOT to be attacks — measured at their own play sites:
     `CaneSwing`/`CaneSwing Idle` drive their swing_state Swing BlendSpace (the hook swing;
     the pendulum motion is the NODE's, the clip is a near-static hang — max 60 Hz step 5°) and
     `CaneSwing Grab` is the catch (hands snap to the overhead grip in 0.1 s, held from 0.4).
     That is our hook family's exact shape — the state carries the arc, the clip carries the
     hang — and §479's "the repo has no hook clips" is corrected by this measurement, so the
     audit default (the repo clip wins) reaches the two verbs with play sites. `hook_release`
     (our dismount flourish) has no counterpart and stays procedural.

     The hang is ONE-ARMED: right hand on the cane overhead, left hanging free at the hip, at
     both sampled phases (`shots/cane1/godot-hookswing-t040`, `-t105`). An earlier draft of this
     comment called it a "two-paw hang" — that was written from a channel summary rather than
     from a picture, and the frames say otherwise. It matters beyond pedantry: a one-armed hang
     leaves the off hand free, which is what makes our `hook_release` flourish legible when it
     takes the body back. */
  hook_grab:     'CaneSwing Grab',
  hook_swing:    'CaneSwing',
};

/**
 * §479.6 — the elbow-open lever. The user reads the swapped set's elbows as "too tucked in".
 * Measured (tools/armcross.mjs, three-way per clip): the tuck is the SOURCE's own style — the
 * repo authors a bent-arm creep (Walk elbows 69–129°, Run 51–122° interior) where our procedural
 * gaits swung near-straight (142–153°) — and the retarget already OPENS it ~15–19° everywhere
 * (the two rigs' rest arm directions differ ~14.5°: source A-pose [.54,−.84] vs RIG3 [.72,−.69],
 * and the world-delta method composes their motion onto OUR wider rest). So this is a taste
 * knob, not a defect repair, and it ships at 0 — faithful to the repo's look, per the audit's
 * own default. Each entry scales the named clip's lowerArm rotations toward bind by the given
 * fraction: 0 = the source's fold, 1 = forearms at rest (fully open). 0.3–0.4 lands the Walk
 * mid-swing elbow within ~10° of the old procedural look (predicted from the angle scaling,
 * verified by the anim.test arm through the real FK; on-camera pair in shots/elb1-*).
 * A capture/hardware A-B can override per boot via `globalThis.__ELBOW_OPEN = {walk: 0.35}` —
 * the same pre-module seam as `__ANIM_AB`. The hardware-review sheet carries the tuning row.
 */
export const GODOT_ELBOW_OPEN = {};

function elbowOpenFor(game) {
  let over = null;
  try { over = globalThis.__ELBOW_OPEN || null; } catch { /* plain hosts */ }
  const k = { ...GODOT_ELBOW_OPEN, ...(over || {}) }[game] || 0;
  return k > 0 ? Math.min(k, 1) : 0;
}

/** lowerArm tracks scaled toward bind by k — the one transform behind the lever above. */
function openElbows(clip, k) {
  if (!k) return clip;
  const I = new THREE.Quaternion();
  const q = new THREE.Quaternion();
  const bones = clip.bones.map((tr) => {
    if (tr.name !== 'lowerArmL' && tr.name !== 'lowerArmR') return tr;
    const out = new Float32Array(tr.q.length);
    for (let i = 0; i < tr.q.length; i += 4) {
      q.set(tr.q[i], tr.q[i + 1], tr.q[i + 2], tr.q[i + 3]);
      q.slerp(I, k);                       // shrink the fold toward bind by k, same axis
      out[i] = q.x; out[i + 1] = q.y; out[i + 2] = q.z; out[i + 3] = q.w;
    }
    return { ...tr, q: out };
  });
  return { ...clip, bones };
}

/**
 * §479.8 — a raw clip cut to [from, until] of its own timeline, keys rebased to t=0. Cuts land
 * on the emitter's 0.05 s key grid, so no key is interpolated, only dropped.
 *
 * Its live use is `until` alone, cutting dead tails: `PickPocket` is exported as a 4 s
 * idle-bake whose motion is over by ~0.6 s, and it ships cut to the 1.1 s the pickpocket state
 * actually spends on it. `from` exists and is tested, but NOTHING ships with a head trim, and
 * that is the deliberate outcome of §479.8's correction rather than an accident: the first pass
 * of the combat port trimmed 0.25–0.30 s off `Canehit`'s head to "skip the windup" and thereby
 * deleted the strike itself (see the alias table — the clip contacts at t 0.10, the fast moment
 * late in it is the recovery). A head trim on an authored clip removes an action, not a pause;
 * it needs a measurement of what is inside the cut before it is used again.
 */
function trimRaw(raw, from = 0, until = raw.dur) {
  if (!from && until >= raw.dur) return raw;
  const keys = raw.keys.filter((k) => k.t >= from - 1e-6 && k.t <= until + 1e-6)
    .map((k) => ({ ...k, t: +(k.t - from).toFixed(4) }));
  return {
    ...raw, dur: +(until - from).toFixed(4), keys,
    events: raw.events ? raw.events.filter((e) => e.t >= from && e.t <= until)
      .map((e) => ({ ...e, t: e.t - from })) : raw.events,
  };
}

/** A raw authoring-format clip replayed over a different duration (events rescale with it). */
function retimeRaw(raw, dur) {
  if (!dur || dur === raw.dur) return raw;
  const k = dur / raw.dur;
  return {
    ...raw, dur,
    keys: raw.keys.map((key) => ({ ...key, t: +(key.t * k).toFixed(4) })),
    events: raw.events ? raw.events.map((e) => ({ ...e, t: e.t * k })) : raw.events,
  };
}

const MIXAMO_ALIAS = {
  /* game name        source            what the geometry says it actually is */
  idle_confident:     'idle_side',      // the ONLY standing idle in the set; near-motionless (Σ20° of articulation)
  crouch_idle:        'idle_01',        // deep crouch — hips 0.47 m against RIG3's 0.886 m bind
  sneak_idle:         'idle_other',     // same crouch, different fidget
  walk:               'walk_forward',   // stride 3.27 m/cycle measured, hips 11-15 cm below bind
  sneak_walk:         'walk_forward_02',// lower again (hips 0.69) and shorter cycle — reads as a creep
  run:                'run',
  run_fast:           'run',            // no second run in the source; the tree needs the node filled
  jump_rise:          'jump_from_ground',
  jump_apex:          'fall_pose_01',   // a 2-key static pose; holding it is all it can do
  jump_fall:          'airtime_01',
  ledge_hang:         'hang_loose',
  ledge_shimmy_l:     'hang_crawl_left',
  ledge_shimmy_r:     'hang_crawl_right',
  pole_climb:         'pole_up',
};

/** Bones RIG3 has and Mixamo does not — the fill list, derived rather than typed twice. */
function donorBones(mixClip) {
  const has = new Set(mixClip.bones.map((t) => t.name));
  return (name) => !has.has(name);
}

/** A donor track replayed over a different duration. Never mutates the shared original. */
function timeScale(track, k) {
  if (k === 1) return track;
  const times = Float32Array.from(track.times, (t) => t * k);
  return { ...track, times };
}

/**
 * Mixamo tracks + the procedural counterpart's tracks for everything Mixamo lacks.
 * `fill = false` gives the pure arm.
 */
function spliceClip(name, mixRaw, donor, fill) {
  const m = compile(name, mixRaw);
  if (!fill || !donor) return m;
  const k = donor.dur > 0 ? m.dur / donor.dur : 1;
  const wants = donorBones(m);
  const bones = m.bones.slice();
  for (const tr of donor.bones) if (wants(tr.name)) bones.push(timeScale(tr, k));
  const scales = m.scales.slice();
  for (const tr of donor.scales) if (wants(tr.name)) scales.push(timeScale(tr, k));
  return {
    ...m,
    bones,
    scales,
    cane: donor.cane ? timeScale(donor.cane, k) : null,
    hold: Math.min(m.dur, donor.hold * k),
    mask: donor.mask || null,
    /* Events are filled by the same rule as bones: the source's own when it has any (the
       emitters derive footsteps for real gaits), else the donor's — time-scaled — so a swap
       cannot silently mute a landing thud or a climb's hand-beat. Donor events live in
       [0, donor.dur], so scaled they live in [0, m.dur] by construction. */
    events: m.events.length ? m.events : donor.events.map((e) => ({ ...e, t: e.t * k })),
  };
}

/**
 * `?anim=` is read at module-load time, the same seam and the same fall-through as `?char=` in
 * `main.js`: a URL param is the only thing reliably set before this module evaluates, with
 * `globalThis.__ANIM_AB` for a runner that boots the page itself. An unknown, misspelled or
 * absent token resolves to `godot` — **the repo's audited movement clips are the shipped
 * default, by the user's instruction; the all-procedural set is one token away (`?anim=proc`),
 * an A/B choice with no `src/` edit and no arm to install.** (Until the FrontFlip commit the
 * default was `proc` and this comment said restoring it was the absence of a token; that claim
 * is deliberately inverted now, and the regime tests were re-derived from the new claim rather
 * than patched around it.)
 */
/**
 * The fall-through, in ONE place. It has to be here rather than at the URL read, because every
 * caller has to get the same answer: a test, a capture runner and the browser must not disagree
 * about what `'mixmao'` means. Returning the raw token to one caller and the resolved one to
 * another is how an arm gets mislabelled while behaving correctly, which is the worst combination.
 */
const REGIMES = ['proc', 'mixamo', 'mixamo-pure', 'godot', 'godot-pure'];
function normaliseRegime(raw) {
  const t = String(raw ?? '').trim().toLowerCase();
  return REGIMES.includes(t) ? t : 'godot';
}

function animRegime() {
  let raw = '';
  try {
    if (typeof location !== 'undefined' && location.search) raw = new URLSearchParams(location.search).get('anim') || '';
    if (!raw && typeof globalThis !== 'undefined' && globalThis.__ANIM_AB != null) raw = String(globalThis.__ANIM_AB);
  } catch { /* plain-module hosts have no location; that is the test path */ }
  return normaliseRegime(raw);
}

/** Build the table this module samples. Exported so tests can build any regime without a URL. */
export function buildClipSet(raw) {
  const regime = normaliseRegime(raw);
  const table = Object.create(null);
  const origin = Object.create(null);
  for (const n in CLIPS) { table[n] = CLIPS[n]; origin[n] = 'proc'; }
  if (regime === 'proc') return { table, origin, regime, unused: [] };
  const fill = !regime.endsWith('-pure');
  const godot = regime.startsWith('godot');
  const SRC = godot ? GODOT_CLIPS : MIXAMO_CLIPS;
  const ALIAS = godot ? GODOT_ALIAS : MIXAMO_ALIAS;
  const tag = godot ? 'godot' : 'mixamo';
  const used = new Set();
  for (const [game, spec] of Object.entries(ALIAS)) {
    const src = typeof spec === 'string' ? spec : spec.src;
    const srcRaw = SRC[src];
    if (!srcRaw || !CLIPS[game]) continue;        // a regenerated module that dropped a clip degrades
    /* `trim`/`until` cut the source to the window that carries the read (§479.8); `dur` pins a
       delivered duration (the flip's window); `rate` pins a delivered PLAYBACK RATE (the
       launch's pace) — dur = authored / rate, so the constant in the table is the measured
       number itself, not its reciprocal baked by hand. `events` hand-carries event times the
       donor-inherit rule would mis-scale (a trimmed strike is not a scaled donor thud). */
    const o = typeof spec === 'object' ? spec : null;
    let timed = o && (o.trim || o.until) ? trimRaw(srcRaw, o.trim || 0, o.until ?? srcRaw.dur) : srcRaw;
    if (o && o.dur) timed = retimeRaw(timed, o.dur);
    else if (o && o.rate) timed = retimeRaw(timed, +(timed.dur / o.rate).toFixed(4));
    if (o && o.events) timed = { ...timed, events: o.events };
    let built = spliceClip(game, timed, CLIPS[game], fill);
    if (godot) built = openElbows(built, elbowOpenFor(game));   // §479.6 — ships at 0, see above
    /* SOURCE IDENTITY, carried on the clip itself rather than looked up in a side table (§525).
       Two game clips with the same `source` are the SAME authored motion under two names — which
       is the normal case for an imported set with fewer clips than we have verbs (their tree has
       ONE ground attack, so all three combo slots are `godot:Canehit`). `play()` uses this to
       refuse to layer a motion on top of itself; see the one-shot coalesce there for why an
       average of one arc with itself is not a pose the animator ever drew. Procedural clips
       carry NO source — each is its own motion — so the rule cannot reach them. */
    built = { ...built, source: `${tag}:${src}` };
    /* EXCLUSION GROUP travels with the game NAME, not with the data (§526). `spliceClip` returns
       an explicit field list built from the imported clip, so `excl` would otherwise be dropped
       here and silently again in the `-pure` arms — leaving the imported regimes layerable where
       the procedural one is not. Whether two clips may be live together is a statement about the
       action slot, so it is re-applied from the procedural def for every regime. */
    if (CLIPS[game].excl) built.excl = CLIPS[game].excl;
    table[game] = built;
    origin[game] = `${tag}:${src}`;
    used.add(src);
  }
  return { table, origin, regime, unused: Object.keys(SRC).filter((n) => !used.has(n)) };
}

const SET = buildClipSet(animRegime());
/** The clip table in force this boot. `proc` unless a token said otherwise. */
export const ACTIVE = SET.table;
export const CLIP_REGIME = SET.regime;
export const CLIP_ORIGIN = SET.origin;

/* Nodes of the locomotion tree. Eight of them: two axes, speed × stance. */
const TREE = [
  { clip: 'idle_confident', stance: 0, i: 0 },
  { clip: 'walk', stance: 0, i: 1 },
  { clip: 'run', stance: 0, i: 2 },
  { clip: 'run_fast', stance: 0, i: 3 },
  { clip: 'sneak_idle', stance: 1, i: 0 },
  { clip: 'sneak_walk', stance: 1, i: 1 },
  { clip: 'crouch_idle', stance: 2, i: 0 },
  { clip: 'crouch_walk', stance: 2, i: 1 },
];

/** Clips MOVEMENT plays that mean "let the tree drive", not "override the body". */
const TREE_CLIPS = {
  idle_confident: 0, idle_bored: 0, idle_look: 0,
  walk: 0, run: 0, run_fast: 0,
  sneak_idle: 1, sneak_walk: 1,
  crouch_idle: 2, crouch_walk: 2,
};

/** Clips whose feet are not on the floor — foot IK must keep its hands off them. */
const AIRBORNE = new Set([
  'jump_rise', 'jump_apex', 'jump_fall', 'double_jump', 'paraglide',
  'wall_run_l', 'wall_run_r', 'wall_jump', 'wall_cling',
  'ledge_hang', 'ledge_shimmy_l', 'ledge_shimmy_r',
  'hook_grab', 'hook_swing', 'hook_release',
  'pole_climb', 'pole_slide', 'pole_swing',
  'rail_slide', 'rail_walk', 'balance_idle',
  'spire_land', 'spire_balance', 'perch_idle',
  'dive_attack', 'roll', 'land_roll', 'crawl', 'ko',
]);

/** Idles get breathing; a run does not need a chest wobble on top of the hammering. */
const BREATHES = new Set([
  'idle_confident', 'idle_bored', 'idle_look', 'perch_idle', 'balance_idle',
  'sneak_idle', 'crouch_idle', 'ledge_hang', 'wall_cling', 'spire_balance', 'ko',
]);

const TRACK_MAX = 6;
const IMPULSE_MAX = 4;
const D2R = Math.PI / 180;

/* ---- module-scope scratch — update() allocates nothing ------------------- */
const _q0 = new THREE.Quaternion();
const _q1 = new THREE.Quaternion();
const _q2 = new THREE.Quaternion();
const _v0 = new THREE.Vector3();
const _v1 = new THREE.Vector3();
const _w = new Float32Array(TREE.length);
const _stance = new Float32Array(3);

const clamp01 = (v) => (v < 0 ? 0 : v > 1 ? 1 : v);

/* ========================================================================== */

export class Animation {
  /** @param {import('../core/Engine.js').Engine} engine */
  constructor(engine) {
    this.engine = engine;
    this.character = null;
    this.rig = null;
    this.pose = null;
    this.ready = false;

    /* ---- locomotion state pushed by MOVEMENT (copied, never retained) ---- */
    this.loco = {
      speed: 0, maxSpeed: 7.2, grounded: true, sneaking: false, crouching: false,
      airborne: false, verticalVelocity: 0, turnRate: 0, slope: 0, surface: 'stone',
    };
    this.smoothSpeed = 0;
    this.prevSpeed = 0;
    this.accel = 0;

    /* ---- tree ---- */
    this.stanceW = new Float32Array([1, 0, 0]);
    this.stanceHint = 0;
    this.treeW = 1;
    this.phase = 0;          // shared stride phase, 0..1
    this.treeTime = 0;       // free-running clock for the non-strided idles
    this.turnPhase = 0;
    this.turnW = 0;
    this._treeEvClip = null;
    this._treePhasePrev = 0;

    /* ---- tracks ---- */
    this.tracks = [];
    for (let i = 0; i < TRACK_MAX; i++) {
      this.tracks.push({
        clip: null, time: 0, prevTime: 0, w: 0, target: 0, fade: 0.12,
        loop: true, speed: 1, lock: false, base: false, ending: false,
      });
    }

    /* ---- additive ---- */
    this.lean = { bank: 0, pitch: 0 };
    this.squash = 0;
    this.squashT = -1;
    this.breath = 0;

    /* ---- impulses ---- */
    this.impulses = [];
    for (let i = 0; i < IMPULSE_MAX; i++) {
      this.impulses.push({ bone: '', dir: new THREE.Vector3(), strength: 0, decay: 6, life: 0, dur: 0.45, active: false });
    }

    /* ---- events ---- */
    this._listeners = new Map();
    this._evtPayload = { surface: 'stone', foot: 'L', power: 1, index: 0, force: 0 };

    /* ---- cane ---- */
    this.canePivot = null;
    this.caneBase = new THREE.Quaternion();
    this.caneCur = new THREE.Quaternion();
    this.caneTarget = new THREE.Quaternion();
    this.caneHas = false;

    /* ---- freeze ---- */
    this.frozen = null;
    this.frozenT = 0;

    this.lookTarget = new THREE.Vector3();
    this.lookOn = false;
    this._warned = Object.create(null);
    this._ikW = 1;

    /** Which clip data is driving the rig this boot. `'proc'` unless `?anim=` said otherwise. */
    this.clipRegime = CLIP_REGIME;
  }

  /** `'proc'` or `'mixamo:<source clip>'` — which data a given name resolves to. */
  clipOrigin(name) { return CLIP_ORIGIN[name] || null; }

  /* ====================================================================== */
  /*  init                                                                  */
  /* ====================================================================== */

  async init() {
    if (MISSING.length) {
      this.engine.warn(`ANIMATION: clips missing from Clips.js: ${MISSING.join(', ')}`);
    }
    /* Only in a non-default regime, and deliberately through the warning channel: §4.5 routes
       `engine.warnings` into report.json, so a capture of an A/B arm carries proof of WHICH arm it
       was inside its own artefact. §186's contamination hazard is exactly the case where a frame
       and its label are recorded in two different places. */
    if (CLIP_REGIME !== 'godot') {
      const n = Object.values(CLIP_ORIGIN).filter((o) => o !== 'proc').length;
      const src = CLIP_REGIME.startsWith('mixamo') ? 'MixamoClips.js' : 'GodotClips.js';
      this.engine.warn(`ANIMATION: clip regime "${CLIP_REGIME}" — ${n ? `${n}/${CLIP_NAMES.length} clips from ${src}, the rest` : 'all 52 clips'} `
        + `hand-authored. Default is "godot" (§478); ?anim= selects.`);
    }
    this._bind();
    // CHARACTER may still be building (or may have failed); pick it up when it lands.
    this._offReady = this.engine.on('characterReady', () => this._bind());
  }

  /** Attach to SlyModel. Safe to call repeatedly; a no-op once it has taken. */
  _bind() {
    if (this.ready) return true;
    const ch = this.engine.get('character');
    if (!ch?.bones?.hips || !ch.boneNames?.length) return false;

    this.character = ch;
    this.rig = new Rig(this.engine, ch);
    if (!this.rig.ok) {
      if (!this._warned.rig) {
        this._warned.rig = 1;
        this.engine.warn('ANIMATION: SlyModel skeleton is incomplete — running without a rig.');
      }
      return false;
    }
    this.pose = new PoseBuffer(ch.boneNames);

    const pivot = ch._attachPoints?.cane || null;
    if (pivot) {
      this.canePivot = pivot;
      this.caneBase.copy(pivot.quaternion);
      this.caneCur.identity();
      this.caneTarget.identity();
    }

    this.ready = true;
    // Start on the money pose rather than one frame of bind.
    this.play('idle_confident', { fade: 0 });
    return true;
  }

  /* ====================================================================== */
  /*  §4.7 public API                                                       */
  /* ====================================================================== */

  play(clip, opts) {
    const name = typeof clip === 'string' ? clip : clip?.name;
    const c = ACTIVE[name];
    if (!c) {
      if (!this._warned[`c:${name}`]) {
        this._warned[`c:${name}`] = 1;
        this.engine.warn(`ANIMATION: unknown clip "${name}" — ignored.`);
      }
      return null;
    }
    const fade = opts?.fade ?? ANIM_TUNE.fade;
    const loop = opts?.loop !== false;
    const speed = opts?.speed ?? 1;
    const weight = opts?.weight ?? 1;
    const lock = !!opts?.lock;

    // A locked clip owns the body until it is done.
    for (const tr of this.tracks) {
      if (tr.clip && tr.lock && tr.w > 0.02 && !tr.ending && tr.clip !== c) return null;
    }

    const stance = TREE_CLIPS[name];
    if (stance !== undefined) {
      // MOVEMENT is describing locomotion — hand the body to the blend tree, which knows
      // more about it (real speed, real turn rate) than a single clip name does.
      this.stanceHint = stance;
      for (const tr of this.tracks) if (tr.clip && !tr.lock) this._end(tr, fade || ANIM_TUNE.treeFade);
      return null;
    }

    // Already running? Retarget it instead of restarting — MOVEMENT re-asserts base clips
    // every frame and a restart would stutter the cycle.
    for (const tr of this.tracks) {
      if (tr.clip === c && !tr.ending) {
        tr.target = weight; tr.loop = loop || tr.loop; tr.speed = speed; tr.lock = tr.lock || lock;
        if (loop) this._demoteOthers(tr, fade);
        return tr;
      }
    }

    /**
     * ONE-SHOT COALESCE (§525) — a motion may not be layered on top of itself.
     *
     * THE DEFECT. `Canehit` is the reference's ONLY ground attack (censused by content in §525,
     * not taken on the strength of its name), so all three of our combo slots resolve to it.
     * Mashing attack re-swings at `_elapsed >= _t * 0.55` = 0.154 s against a 0.5 s clip, so the
     * old code had THREE tracks of the same arc live at three different phases, every one of them
     * pinned at weight 1.0 for 0.30 s. `PoseBuffer.addQuat` averages them, and the average of one
     * arc with itself out of phase is not a pose from that arc: measured at up to 32.3° from the
     * NEAREST hand orientation anywhere in the authored clip (`tools/comboseam.mjs`). The cane is
     * socketed rigidly to `handR` (`SlyModelDLRig`), so an invented hand orientation is an
     * invented cane direction — which is exactly the cane-trailing frame §479.9 photographed and
     * left unpatched pending the census.
     *
     * THE RULE. When a one-shot fires and a live one-shot is already playing the same `source`,
     * END the old one instead of adding a fourth voice. The two then cross-fade — old weight
     * strictly falling, new strictly rising — which is an ordinary transition rather than an
     * equal-weight average of three phases of one curve.
     *
     * WHY THIS SHAPE. It is the reference's own answer, adapted rather than ported: their tree
     * has a SINGLE `Hit Shot` AnimationNodeOneShot (fadein 0.1, fadeout 0.1) that every square
     * press re-fires (`player__sly.gd:640` sets `transition_request` + `ONE_SHOT_REQUEST_FIRE`,
     * with no combo index anywhere in the script) — so their attack never has two instances live
     * either. We keep our own three-slot chain, its lunges, its per-slot events and its shake;
     * only the layering of identical motion is removed.
     *
     * THE SECOND HALF OF THE CLASS (§526) — a motion averaged with one it should have REPLACED.
     *
     * `source` only catches one arc layered on itself, which is the shape the imported set makes
     * because their corpus has a single attack. The procedural set has three genuinely DIFFERENT
     * combo clips and carries no `source` at all, so the rule above could not reach it — and it
     * had the same defect for the same reason: `Combo.update` re-swings at 0.154 s into a 0.46 s
     * clip and nothing ever ended the outgoing strike, so three different strikes ran at full
     * weight together for 15 frames, 29.8° off-manifold.
     *
     * Averaging three DIFFERENT strikes is not automatically wrong — that is what blending is
     * for — but these three are not alternatives the body can hold at once; they are three
     * renditions of ONE action slot, and slot 2 is meant to INTERRUPT slot 1, not to be summed
     * with it. What that summing destroys here is the escalation: the three are authored with
     * rising reach (0.3105 → 0.3781 → 0.4653 m solo, the finisher furthest), and the layered
     * chain flattens them to 0.3467 / 0.3630 / 0.3490 — the finisher, the pose `combat` freezes
     * on, loses 25% of its lunge while slot 1 is dragged 12% ABOVE its own authored reach by the
     * strike overlapping it. Neither number is visible without attributing per slot against that
     * slot's OWN clean peak (§526.1 — the single `clean` scalar that was right for one repeated
     * clip is the wrong yardstick for three different ones).
     *
     * So exclusivity is declared on the clip as `excl`, beside `source`, and the rule takes
     * either. It is a property of the action SLOT rather than of the data behind it, which is
     * why `buildClipSet` copies it from the procedural def onto every imported build of the same
     * game name: swapping the data must not change whether two clips may coexist.
     *
     * WHAT IT DOES NOT TOUCH. A clip carries no `excl` unless its def asks for one, and none
     * carries a `source` in the procedural set, so both predicates are opt-in and the reachable
     * set is a printed list rather than an assurance (see the census in §526.2). Distinct sources
     * and distinct groups never match — `hook_grab`/`hook_release` are different verbs, and the
     * probe in §525 established the release is not even the same authored shape. Loop clips take
     * the `_demoteOthers` path above and never reach here; a re-fire of the SAME clip takes the
     * retarget path above and never reached here either.
     */
    if (!loop) {
      for (const tr2 of this.tracks) {
        if (!tr2.clip || tr2.ending || tr2.loop || tr2.clip === c) continue;
        const sameMotion = !!c.source && tr2.clip.source === c.source;   // §525 — the same arc twice
        const sameSlot = !!c.excl && tr2.clip.excl === c.excl;           // §526 — one action slot
        if (sameMotion || sameSlot) this._end(tr2, fade);
      }
    }

    const tr = this._alloc();
    tr.clip = c;
    tr.time = 0; tr.prevTime = -1e-4;
    tr.w = fade > 0 ? 0 : weight;
    tr.target = weight;
    tr.fade = Math.max(0.001, fade);
    tr.loop = loop;
    tr.speed = speed;
    tr.lock = lock;
    tr.base = loop;
    tr.ending = false;
    if (loop) this._demoteOthers(tr, fade);
    return tr;
  }

  stop(clip, fade = ANIM_TUNE.fade) {
    const name = typeof clip === 'string' ? clip : clip?.name;
    for (const tr of this.tracks) if (tr.clip?.name === name) this._end(tr, fade);
  }

  isPlaying(clip) {
    const name = typeof clip === 'string' ? clip : clip?.name;
    if (this.frozen) return this.frozen.name === name;
    for (const tr of this.tracks) if (tr.clip?.name === name && tr.w > 0.01 && !tr.ending) return true;
    // The tree is "playing" whichever locomotion clip currently carries the most weight.
    if (TREE_CLIPS[name] !== undefined && this.treeW > 0.05) {
      this._treeWeights();
      for (let i = 0; i < TREE.length; i++) if (TREE[i].clip === name && _w[i] > 0.15) return true;
    }
    return false;
  }

  /** Continuous locomotion state. Fields are copied — the caller reuses its object. */
  setLocomotion(s) {
    if (!s) return;
    const L = this.loco;
    L.speed = +s.speed || 0;
    L.maxSpeed = +s.maxSpeed || 7.2;
    L.grounded = !!s.grounded;
    L.airborne = s.airborne !== undefined ? !!s.airborne : !s.grounded;
    L.sneaking = !!s.sneaking;
    L.crouching = !!s.crouching;
    L.verticalVelocity = +s.verticalVelocity || 0;
    L.turnRate = +s.turnRate || 0;
    L.slope = +s.slope || 0;
    L.surface = s.surface || 'stone';
  }

  setLookAt(worldPos) {
    if (worldPos) { this.lookTarget.copy(worldPos); this.lookOn = true; }
    else this.lookOn = false;
    this.rig?.setLookAt(this.lookOn ? this.lookTarget : null);
  }

  /**
   * A shove on a bone. `bone: 'root'` is the landing/impact channel — rotating the root would
   * tip the whole character through the floor, so it drives the squash spring instead, which
   * is what a body actually does when something hits it hard.
   */
  addImpulse(imp) {
    if (!imp) return;
    if (!imp.bone || imp.bone === 'root' || imp.bone === 'hips') {
      const s = clamp01(Math.abs(imp.strength ?? 1));
      if (s > this.squash * 0.6) { this.squashT = 0; this.squash = Math.max(this.squash, s); }
      this._emit('land', { force: s * 18, surface: this.loco.surface });
      if (!imp.bone || imp.bone === 'root') return;
    }
    let slot = null;
    for (const s of this.impulses) if (!s.active) { slot = s; break; }
    if (!slot) { slot = this.impulses[0]; for (const s of this.impulses) if (s.life < slot.life) slot = s; }
    slot.bone = imp.bone;
    slot.dir.copy(imp.dir || _v0.set(0, -1, 0));
    if (slot.dir.lengthSq() < 1e-8) slot.dir.set(0, -1, 0);
    slot.strength = THREE.MathUtils.clamp(imp.strength ?? 1, -3, 3);
    slot.decay = imp.decay ?? 6;
    slot.dur = 0.34 + 0.5 / Math.max(1, slot.decay);
    slot.life = slot.dur;
    slot.active = true;
  }

  /** Screenshot harness: hold one frame. `phase` (0..1) is a debug extra for filmstrips. */
  freezePose(name, phase) {
    const c = ACTIVE[name];
    if (!c) {
      this.engine.warn(`ANIMATION: freezePose("${name}") — no such clip.`);
      return false;
    }
    this.frozen = c;
    this.frozenT = phase === undefined || phase === null
      ? c.hold
      : THREE.MathUtils.clamp(phase, 0, 1) * c.dur;
    // Springs must not drag a stale swing into a still frame.
    this.rig?.settle();
    /* `caneCur` is the one damped integrator of the character that does NOT live on Rig, so
       `settle()` — which clears the tail, the brim/ear springs, hipsVel, the look chain and
       hipDrop — never reached it. `_applyCane`'s `k = 1` branch masks that for as long as
       `this.frozen` holds, which is why it has never shown up in a still; the moment anything
       renders a frame with the freeze not in force, this carries a lag state that converges
       toward its target and never arrives (measured: still moving 9.2 cm of tip between frame
       17 and frame 120). Reset it here so the invariant is the same one `settle()` states,
       rather than one that depends on a branch elsewhere staying true. */
    this.caneCur.identity();
    this.caneHas = false;
    this.lean.bank = 0; this.lean.pitch = 0;
    this.squash = 0; this.squashT = -1;
    this.breath = 0;
    for (const s of this.impulses) s.active = false;
    this._ikW = AIRBORNE.has(name) ? 0 : 1;
    return true;
  }

  unfreezePose() {
    if (!this.frozen) return;
    this.frozen = null;
    this.rig?.settle();
  }

  clipNames() { return CLIP_NAMES.slice(); }

  /** 'footstep' {surface,foot} · 'cane_hit' {index} · 'land' {force} */
  onEvent(name, fn) {
    if (typeof fn !== 'function') return () => {};
    if (!this._listeners.has(name)) this._listeners.set(name, new Set());
    this._listeners.get(name).add(fn);
    return () => this._listeners.get(name)?.delete(fn);
  }

  /* ====================================================================== */
  /*  frame                                                                 */
  /* ====================================================================== */

  update(dt, t) {
    if (!this.ready && !this._bind()) {
      /* Silent until now, and it is the failure that produces §35's symptom. If a capture asks
         for a frozen pose and the rig never binds, `_applyCane` never runs, so the cane renders
         at its bind orientation — measured 1.10 m of hook displacement from where the pose puts
         it — while the frame looks plausible and nothing anywhere says so. `_bind()` returns
         false with no warning when the skeleton has not arrived, so this is the only place that
         can report it. §4.5 routes engine.warnings into report.json; §5 forbids throwing. */
      if (this.frozen && !this._warned.unbound) {
        this._warned.unbound = 1;
        this.engine.warn(
          `ANIMATION: freezePose("${this.frozen.name}") is active but the rig never bound — ` +
          `character and cane are rendering the bind pose, not the clip.`
        );
      }
      return;
    }
    const d = dt > 0 ? Math.min(dt, 1 / 20) : 0;

    this.pose.clear();
    this.caneHas = false;

    if (this.frozen) {
      sampleInto(this.frozen, this.frozenT, this.pose, 1);
      this.caneHas = sampleCane(this.frozen, this.frozenT, this.caneTarget);
    } else {
      this._advance(d, t);
      this._sampleTree(d);
      this._sampleTracks();
      this._additive(d, t);
    }

    this.rig.commit(this.pose);
    this.rig.sampleMotion(d);
    this.rig.yawRate = this.loco.turnRate;

    this._runImpulses(d);
    this.rig.lookAtLayer(d, this.lookOn ? ANIM_TUNE.lookWeight : 0);
    this.rig.springLayer(d, 1);
    this.rig.tailLayer(d, 1);
    this._footIK(d);
    this._applyCane(d);
  }

  /* ---------------------------------------------------------------- tracks */

  _alloc() {
    for (const tr of this.tracks) if (!tr.clip) return tr;
    let worst = this.tracks[0];
    for (const tr of this.tracks) if (tr.w < worst.w && !tr.lock) worst = tr;
    return worst;
  }

  _end(tr, fade) {
    if (!tr.clip || tr.ending) return;
    tr.ending = true;
    tr.lock = false;
    tr.target = 0;
    tr.fade = Math.max(0.001, fade ?? ANIM_TUNE.fade);
  }

  /** A new looping base retires the old one; one-shots are left to finish on top. */
  _demoteOthers(keep, fade) {
    for (const tr of this.tracks) {
      if (tr === keep || !tr.clip) continue;
      if (tr.loop) this._end(tr, fade || ANIM_TUNE.fade);
    }
  }

  _advance(dt, t) {
    const L = this.loco;
    const k = 1 - Math.exp(-ANIM_TUNE.speedSmooth * Math.max(dt, 1e-4));
    this.smoothSpeed += (L.speed - this.smoothSpeed) * k;
    if (dt > 1e-4) {
      const a = (this.smoothSpeed - this.prevSpeed) / dt;
      this.accel += (a - this.accel) * Math.min(1, dt * 8);
    }
    this.prevSpeed = this.smoothSpeed;

    /* stance cross-fade */
    const hint = this.stanceHint;
    const wantSneak = (L.sneaking || hint === 1) && !L.crouching ? 1 : 0;
    const wantCrouch = (L.crouching || hint === 2) ? 1 : 0;
    const sr = 1 - Math.exp(-ANIM_TUNE.stanceRate * Math.max(dt, 1e-4));
    this.stanceW[1] += (wantSneak - this.stanceW[1]) * sr;
    this.stanceW[2] += (wantCrouch - this.stanceW[2]) * sr;
    this.stanceW[0] = Math.max(0, 1 - this.stanceW[1] - this.stanceW[2]);

    /* shared stride phase — the reason the feet don't skate through a blend */
    const stride = this._strideLength();
    let rate = stride > 0 ? this.smoothSpeed / stride : 0;
    if (rate > 0 && rate < ANIM_TUNE.strideMin) rate = ANIM_TUNE.strideMin;
    rate = Math.min(rate, ANIM_TUNE.strideMax);
    this._treePhasePrev = this.phase;
    this.phase = (this.phase + rate * dt) % 1;
    this.treeTime += dt;

    /* turn in place: only meaningful when he is not really going anywhere */
    const still = 1 - clamp01((this.smoothSpeed - ANIM_TUNE.moveFloor) / 1.4);
    const wantTurn = clamp01((Math.abs(L.turnRate) - 0.45) / 2.2) * still * this.stanceW[0];
    this.turnW += (wantTurn - this.turnW) * Math.min(1, dt * 8);
    this.turnPhase = (this.turnPhase + (Math.abs(L.turnRate) / ANIM_TUNE.turnCycle) * dt) % 1;

    /* track fades + playheads */
    let used = 0;
    for (const tr of this.tracks) {
      if (!tr.clip) continue;
      const step = tr.fade > 0 ? dt / tr.fade : 1;
      if (tr.w < tr.target) tr.w = Math.min(tr.target, tr.w + step);
      else if (tr.w > tr.target) tr.w = Math.max(tr.target, tr.w - step);

      tr.prevTime = tr.time;
      const clipRate = tr.clip.stride > 0
        ? Math.min(ANIM_TUNE.strideMax, Math.max(ANIM_TUNE.strideMin, this.smoothSpeed / tr.clip.stride)) * tr.clip.dur
        : 1;
      tr.time += dt * tr.speed * clipRate;

      this._trackEvents(tr);

      if (!tr.loop && tr.time >= tr.clip.dur && !tr.ending) this._end(tr, ANIM_TUNE.fade);
      if (tr.ending && tr.w <= 0.001) { tr.clip = null; tr.w = 0; tr.lock = false; continue; }
      used += tr.w;
    }
    this.treeW = clamp01(1 - used);

    /* landing squash envelope: fast in, ease-out back (§6) */
    if (this.squashT >= 0) {
      this.squashT += dt;
      if (this.squashT > ANIM_TUNE.squashIn + ANIM_TUNE.squashOut) { this.squashT = -1; this.squash = 0; }
    }
    void t;
  }

  /** Weighted mean stride of every moving node — the blend's real ground speed. */
  _strideLength() {
    this._treeWeights();
    let s = 0, w = 0;
    for (let i = 0; i < TREE.length; i++) {
      const c = ACTIVE[TREE[i].clip];
      if (!c?.stride || _w[i] <= 0) continue;
      s += c.stride * _w[i]; w += _w[i];
    }
    for (const tr of this.tracks) {
      if (!tr.clip?.stride || tr.w <= 0) continue;
      s += tr.clip.stride * tr.w; w += tr.w;
    }
    return w > 1e-3 ? s / w : 0;
  }

  /* ------------------------------------------------------------------ tree */

  /** Fill `_w` with the 8 node weights: a speed axis inside each stance. */
  _treeWeights() {
    _w.fill(0);
    _stance[0] = this.stanceW[0]; _stance[1] = this.stanceW[1]; _stance[2] = this.stanceW[2];
    const sp = Math.max(0, this.smoothSpeed);
    const T = ANIM_TUNE;

    // stand: idle → walk → run → run_fast
    if (_stance[0] > 1e-3) this._axis(sp, T.standAxis, _stance[0], 0);
    if (_stance[1] > 1e-3) this._axis(sp, T.sneakAxis, _stance[1], 4);
    if (_stance[2] > 1e-3) this._axis(sp, T.crouchAxis, _stance[2], 6);
    return _w;
  }

  /** Piecewise-linear 1-D blend across `pts` speeds, into `_w` starting at `base`. */
  _axis(sp, pts, weight, base) {
    const n = pts.length;
    if (sp <= pts[0] + 1e-4) { _w[base] += weight; return; }
    if (sp >= pts[n - 1]) { _w[base + n - 1] += weight; return; }
    for (let i = 0; i < n - 1; i++) {
      if (sp <= pts[i + 1]) {
        let f = (sp - pts[i]) / (pts[i + 1] - pts[i]);
        // Ease the idle→move edge so a nudge of the stick doesn't half-play a walk.
        if (i === 0) f = clamp01((sp - ANIM_TUNE.moveFloor) / (pts[1] - ANIM_TUNE.moveFloor));
        _w[base + i] += weight * (1 - f);
        _w[base + i + 1] += weight * f;
        return;
      }
    }
  }

  _sampleTree(dt) {
    if (this.treeW <= 0.001) return;
    this._treeWeights();
    let dom = null, domW = 0;
    for (let i = 0; i < TREE.length; i++) {
      const nw = _w[i];
      if (nw <= 0.002) continue;
      const c = ACTIVE[TREE[i].clip];
      if (!c) continue;
      const time = c.stride > 0 ? this.phase * c.dur : this.treeTime;
      sampleInto(c, time, this.pose, nw * this.treeW);
      if (nw > domW) { domW = nw; dom = c; }
      if (!this.caneHas && nw > 0.4) this.caneHas = sampleCane(c, time, this.caneTarget);
    }

    // Turn-in-place rides on top of the idle: it is a whole-body wind, not a leg cycle.
    if (this.turnW > 0.01) {
      const c = ACTIVE[this.loco.turnRate > 0 ? 'turn_l' : 'turn_r'];
      if (c) sampleInto(c, this.turnPhase * c.dur, this.pose, this.turnW * this.treeW * 0.85);
    }

    this._treeEvents(dom);
    void dt;
  }

  _sampleTracks() {
    for (const tr of this.tracks) {
      if (!tr.clip || tr.w <= 0.001) continue;
      sampleInto(tr.clip, tr.time, this.pose, tr.w);
      if (tr.w > 0.35) {
        if (sampleCane(tr.clip, tr.time, _q0)) {
          if (!this.caneHas) { this.caneTarget.copy(_q0); this.caneHas = true; }
          else this.caneTarget.slerp(_q0, tr.w);
        }
      }
    }
  }

  /* ---------------------------------------------------------------- events */

  _emit(name, data) {
    const set = this._listeners.get(name);
    if (set) for (const fn of set) { try { fn(data); } catch (e) { this.engine.warn(`ANIMATION: "${name}" handler threw: ${e?.message}`); } }
    this.engine.emit(name, data);
  }

  _fire(ev) {
    const p = this._evtPayload;
    p.surface = this.loco.surface;
    p.foot = ev.d?.foot || 'L';
    p.power = ev.d?.power ?? 1;
    p.index = ev.d?.index ?? 0;
    p.force = (ev.d?.force ?? 0) * 18;
    this._emit(ev.n, p);
  }

  /** Fire everything the playhead crossed this frame, wrap included. */
  _trackEvents(tr) {
    const evs = tr.clip.events;
    if (!evs.length) return;
    const dur = tr.clip.dur;
    let a = tr.prevTime, b = tr.time;
    if (b <= a) return;
    if (tr.loop) {
      const la = ((a % dur) + dur) % dur;
      const lb = la + (b - a);
      for (const e of evs) {
        if ((e.t > la && e.t <= lb) || (e.t + dur > la && e.t + dur <= lb)) this._fire(e);
      }
    } else {
      for (const e of evs) if (e.t > a && e.t <= b) this._fire(e);
    }
  }

  /** Locomotion events come off the dominant node's phase, so a blend fires once per step. */
  _treeEvents(dom) {
    if (!dom || !dom.events.length || !dom.stride || this.treeW < 0.35) { this._treeEvClip = dom; return; }
    if (this._treeEvClip !== dom) { this._treeEvClip = dom; return; }
    const a = this._treePhasePrev, b = this.phase;
    const wrapped = b < a;
    for (const e of dom.events) {
      const p = e.t / dom.dur;
      if (wrapped ? (p > a || p <= b) : (p > a && p <= b)) this._fire(e);
    }
  }

  /* -------------------------------------------------------------- additive */

  /**
   * Layers a keyframe should not carry: breath, the lean into a turn or an acceleration, and
   * the landing squash. All post-multiplied onto the sampled pose so they bend the authored
   * shape instead of replacing it.
   */
  _additive(dt, t) {
    const T = ANIM_TUNE;
    const L = this.loco;

    /* lean — bank into the turn, pitch into the acceleration */
    const wantBank = THREE.MathUtils.clamp(-L.turnRate * T.leanTurn, -T.leanTurnMax, T.leanTurnMax)
      * clamp01(this.smoothSpeed / 3.0);
    const wantPitch = THREE.MathUtils.clamp(this.accel * T.leanAccel, -T.leanAccelMax, T.leanAccelMax);
    const lr = 1 - Math.exp(-T.leanRate * Math.max(dt, 1e-4));
    this.lean.bank += (wantBank - this.lean.bank) * lr;
    this.lean.pitch += (wantPitch - this.lean.pitch) * lr;
    if (Math.abs(this.lean.bank) > 0.05 || Math.abs(this.lean.pitch) > 0.05) {
      const b = this.lean.bank, p = this.lean.pitch;
      this._rot('hips', p * 0.5, 0, b * 0.55);
      this._rot('spine', p * 0.25, 0, b * 0.22);
      this._rot('chest', p * 0.25, 0, b * 0.23);
      // The head stays level — it is the one part of him that never commits.
      this._rot('neck', -p * 0.3, 0, -b * 0.25);
      this._rot('head', -p * 0.3, 0, -b * 0.35);
    }

    /* breathing, idles only */
    let breathW = 0;
    if (this.treeW > 0.2 && this.smoothSpeed < 0.6) breathW = this.treeW;
    for (const tr of this.tracks) if (tr.clip && BREATHES.has(tr.clip.name)) breathW = Math.max(breathW, tr.w);
    if (breathW > 0.01) {
      const ph = t * T.breathRate * Math.PI * 2;
      const s = Math.sin(ph);
      const a = T.breathAmp * breathW;
      this._rot('chest', -a, 0, 0);
      this._rot('spine', a * 0.45, 0, 0);
      this._rot('neck', -a * 0.35 * s, 0, 0);
      this._scale('chest', 1 + T.breathScale * s * breathW, 1 + T.breathScale * 0.6 * s * breathW, 1 + T.breathScale * s * breathW);
      this._rot('shoulderL', 0, 0, -a * 0.4 * s);
      this._rot('shoulderR', 0, 0, a * 0.4 * s);
    }

    /* landing squash */
    if (this.squashT >= 0 && this.squash > 0.01) {
      const T2 = ANIM_TUNE;
      // Straight in over 90 ms, then an ease-out cubic release — the recoil reads as elastic.
      const u = clamp01((this.squashT - T2.squashIn) / T2.squashOut);
      const env = this.squashT <= T2.squashIn
        ? this.squashT / T2.squashIn
        : (1 - u) * (1 - u) * (1 - u);
      const s = env * this.squash * T2.squashScale;
      if (s > 0.002) {
        this._scale('hips', 1 + s * 0.9, 1 - s, 1 + s * 0.85);
        this._scale('chest', 1 + s * 0.6, 1 - s * 0.7, 1 + s * 0.55);
        this._scale('head', 1 + s * 0.35, 1 - s * 0.4, 1 + s * 0.3);
        const knee = s * ANIM_TUNE.squashKnee / T2.squashScale;
        this._rot('upperLegL', -knee * 0.55, 0, 0);
        this._rot('upperLegR', -knee * 0.55, 0, 0);
        this._rot('lowerLegL', knee, 0, 0);
        this._rot('lowerLegR', knee, 0, 0);
        this._rot('footL', -knee * 0.42, 0, 0);
        this._rot('footR', -knee * 0.42, 0, 0);
        this._rot('spine', knee * 0.12, 0, 0);
      }
    }
  }

  _rot(bone, x, y, z) {
    if (!x && !y && !z) return;
    eulerDeg(x, y, z, _q1);
    this.pose.rotate(bone, _q1);
  }

  _scale(bone, x, y, z) { this.pose.mulScale(bone, x, y, z); }

  /* ------------------------------------------------------------- impulses */

  _runImpulses(dt) {
    for (const s of this.impulses) {
      if (!s.active) continue;
      if (!this.rig.applyImpulse(s, dt)) s.active = false;
    }
  }

  /* ---------------------------------------------------------------- footIK */

  _footIK(dt) {
    let want = this._ikW;
    if (!this.frozen) {
      want = this.loco.grounded ? ANIM_TUNE.ikGround : 0;
      // An airborne authored clip (a swing, a hang) must not have its legs dragged down.
      for (const tr of this.tracks) if (tr.clip && tr.w > 0.5 && AIRBORNE.has(tr.clip.name)) want = 0;
      const r = 1 - Math.exp(-ANIM_TUNE.ikAirRate * Math.max(dt, 1e-4));
      this._ikW += (want - this._ikW) * r;
    } else this._ikW = want;
    const yaw = this.character.root.rotation.y;
    this.rig.footIK(dt, this._ikW, yaw);
  }

  /* ------------------------------------------------------------------ cane */

  /**
   * Re-aim the cane inside the fist. CHARACTER owns where the grip is; ANIMATION owns where
   * the cane points, because "over the shoulder", "hooked on a ring" and "speared at the
   * floor" are animation decisions, not model ones.
   */
  _applyCane(dt) {
    if (!this.canePivot) return;
    if (!this.caneHas) this.caneTarget.identity();
    const k = this.frozen ? 1 : 1 - Math.exp(-16 * Math.max(dt, 1e-4));
    this.caneCur.slerp(this.caneTarget, k);
    this.canePivot.quaternion.copy(this.caneCur).multiply(this.caneBase);
    this.canePivot.updateMatrixWorld(true);
  }

  /* ====================================================================== */

  dispose() {
    this._offReady?.();
    if (this.canePivot) {
      this.canePivot.quaternion.copy(this.caneBase);
      this.canePivot = null;
    }
    this._listeners.clear();
    this.rig?.dispose();
    this.rig = null;
    this.pose = null;
    this.character = null;
    this.ready = false;
  }
}
